# Generated by Django 4.0.3 on 2022-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
