# Generated by Django 4.0.3 on 2022-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_shortener_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
